CREATE table PELATES  (
 KWDIKOS_PELATH VARCHAR(20) NOT NULL,
 AFM_PELATH INTEGER NOT NULL,
 ONOMA VARCHAR(20) NOT NULL,
 EPWNUMO VARCHAR(20) NOT NULL,
 FULO VARCHAR(20) NOT NULL,
 HMMEROMHNIA_GENNHSHS DATE NOT NULL,
 DIEUTHUNSH VARCHAR(20) NOT NULL,
 THLEFWNO INTEGER NOT NULL
 )
 